### ISSUE TITLE
Problem updating database in 2 different scripts running at same time

### ISSUE THREAD

**Issue by ejbp** [louischatriot/nedb#403] opened 2016-04-10 15:20 UTC
I'm trying to use the database in 2 different scripts that run at same time. When I update a document in the script A, the update is not reflected in the script B after a get. I need to restart the script B in order to read the update of script A. 

It appears that when I load the database, it goes into memory and memory is never updated until a restart. Is this a bug or a feature? Do you recommend any solution? 

Thanks.

**Comment by lukasbestle** [comment] 2016-04-10 15:28
This is a duplicate of #353 and #384.

**Comment by louischatriot** [comment] 2016-04-11 09:11
Thanks @lukasbestle, indeed a duplicate. @ejbp the short answer is no it's not possible to do so, and that's not a bug but by design. Achieving that result means creating a server around an instance of NeDB much like what Mongo exposes, but is outside of the scope of this project.

**Closed by louischatriot** 2016-04-11 09:11 UTC
