### ISSUE TITLE
Error: Failed to flush to storage on DB Startup

### ISSUE THREAD

**Issue by tiagolpadua** [louischatriot/nedb#407] opened 2016-04-12 19:55 UTC
I'm running a project inside a vagrant box and get this error on the app startup.

Linux vagrant-ubuntu-trusty-64 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

vagrant@vagrant-ubuntu-trusty-64:/vagrant/alurapic$ npm start

> alurapic@1.0.0 start /vagrant/alurapic
> node server.js

Banco data.db pronto para uso
Servidor escutando na porta: 3000
/vagrant/alurapic/node_modules/nedb/lib/datastore.js:77
    if (err) { throw err; }
               ^

Error: Failed to flush to storage
    at /vagrant/alurapic/node_modules/nedb/lib/storage.js:63:19
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! alurapic@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alurapic@1.0.0 start script 'node server.js'.
npm ERR! This is most likely a problem with the alurapic package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls alurapic
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.13.0-79-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! path npm-debug.log.554385b17e09696d528b9176a40549ad
npm ERR! code ETXTBSY
npm ERR! errno -26
npm ERR! syscall rename

npm ERR! ETXTBSY: text file is busy, rename 'npm-debug.log.554385b17e09696d528b9176a40549ad' -> 'npm-debug.log'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant/alurapic/npm-debug.log

**Comment by tiagolpadua** [comment] 2016-04-12 20:02
Running the same project on the windows host machine solved the problem, it is something related to Vagrant

**Comment by jmversteeg** [comment] 2016-04-14 00:48
I ran into the same issue -- it happens when I run my app in a local docker container via `docker machine` with the nedb storage location specifically set to a shared folder (via VirtualBox).

It has something to do with the fs.fsync method - it seems this causes problems with shared folders inside VMs.

**Comment by louischatriot** [comment] 2016-04-14 06:52
In that case that's not a bug in nedb but in Node itself. That said that is very interesting and I think something worth reporting to the Node team! Closing this.

**Closed by louischatriot** 2016-04-14 06:52 UTC

**Comment by cmgriffing** [comment] 2016-08-28 10:14
I realize this is a closed issue, but it is the highest ranked result for this problem.

I was able to fix this issue in my own environment by making sure that vagrant synced the folder using NFS.

**Comment by matthewjcooper** [comment] 2017-02-18 19:38
Anyone ever figure this out when having the issue with Docker for Windows? I see that @cmgriffing got it to work with using NFS on vagrant, anyway to do the same in docker?

**Comment by mymainmanbrown** [comment] 2017-02-25 16:13
I ran into this as well, running the following under vagrant:

Host: Linux Mint 18
Guest: Ubuntu 16.04
NPM: 4.12
Node: 7.6.0
nedb: 1.8.0

Looking at the source, and to expand on @sgtlambda comment, it appears that this issue occurs as a result of ```fs.fsync``` in ```/lib/storage.js```, and Node's ```fs``` documentation lists Vagrant and Docker in their caveats section for ```fs.watch``` - https://nodejs.org/api/fs.html#fs_fs_watch_filename_options_listener

So it seems until this issue is fixed in Node itself, it can't be fixed in nedb :(

**Comment by toomu** [comment] 2017-05-03 17:06
@mymainmanbrown How do we fix this mac?

**Comment by mymainmanbrown** [comment] 2017-05-05 00:43
@toomu - I don't have a mac, so I don't know the exact steps, but you should only need to figure out mac-specific instructions for step 1 above.  Maybe brew has an NFS server?  Once you get the NFS server running on your mac, the rest of the steps are for vagrant, so they should work exactly the same.

**Comment by Fabryz** [comment] 2018-01-31 16:52
Have this issue with Debian 8 distro (VMWare) under MacOSX, node v8.9.4.
Anyone else got the "Uncaught Error: Failed to flush to storage" issues?

**Comment by 5hanth** [comment] 2018-05-03 22:07
Having this with OSX as host and docker image [romancin/rutorrent-flood:latest](https://hub.docker.com/r/romancin/rutorrent-flood/)

not sure if volumes has got anything to do with this

    volumes: 
      - "./rutorrent-config:/config"
      - "./rutorrent-downloads:/downloads"

**Comment by WebMatrixware** [comment] 2019-06-19 19:29
Did this ever get brought to the node team's attention? I am not finding an issue for it.

**Comment by ericblade** [comment] 2019-10-02 01:23
I recognize that this is old, but .. yeah. Not an internal node problem.  You simply *can't* fsync on some types of file systems. 

It would be a correct solution, if this is triggered via calls to watch, to catch the EINVAL error, and either take the alternative route (watch via poll), or just not watch.

**Comment by didosame** [comment] 2019-12-05 17:43
> Anyone ever figure this out when having the issue with Docker for Windows? I see that @cmgriffing got it to work with using NFS on vagrant, anyway to do the same in docker?

Nothing here?

**Comment by gfaraj** [comment] 2020-01-14 06:51
I also encountered this when deploying my app within a docker container with a bind mount. Any workarounds or plans to fix it?

**Comment by WebMatrixware** [comment] 2020-02-10 16:05
> I recognize that this is old, but .. yeah. Not an internal node problem. You simply _can't_ fsync on some types of file systems.
> 
> It would be a correct solution, if this is triggered via calls to watch, to catch the EINVAL error, and either take the alternative route (watch via poll), or just not watch.

Any plans on nedb to correct the logic and have a container viable version? I have read the comments on setting up custom storage properties to get around this with nfs, but that is enough of a hassle that most devs will just move on and use something else.

**Comment by riteshgp7** [comment] 2021-01-20 05:06
I'm runing nedb in aws lambda with node js but it's throw error "Failed to flush to storage" when try to load database.

**Serverless application
AWS Lambda with node 12.x**

Error: Failed to flush to storage
    at /var/task/lambdas.js:2:6460637
    at FSReqCallback.oncomplete (fs.js:156:23) {
  errorOnFsync: [Error: EINVAL: invalid argument, fsync] {
    errno: -22,
    code: 'EINVAL',
    syscall: 'fsync'
  },
  errorOnClose: null
}
