### ISSUE TITLE
How to search from a particular database?

### ISSUE THREAD

**Issue by pravin-d** [louischatriot/nedb#332] opened 2015-11-29 14:44 UTC
Suppose I have more than one db "Users" and "Admin", how does db.find() work in this case ?

**Comment by lukasbestle** [comment] 2015-11-29 14:49
So you want to search in multiple datastores (NeDB files) at the same time? Or what are you trying to achieve?

**Comment by pravin-d** [comment] 2015-11-30 11:41
Yup..

**Comment by lukasbestle** [comment] 2015-11-30 11:46
That does not work out of the box, as multiple datastores are multiple JavaScript objects. You can do the following though:

- Write a function that takes a datastore object, runs the search on it and returns a promise that gets the results after NeDB has found the data.
- Use `Promise.all` to call a function after both datastores have completed the find operation.
- Merge the results.

If you need any specific code, don't hesitate to ask.

**Comment by louischatriot** [comment] 2015-11-30 13:42
Thanks, Lukas. Closing this as not a bug nor feature requesT.

**Closed by louischatriot** 2015-11-30 13:42 UTC

**Comment by pravin-d** [comment] 2015-11-30 14:26
Thank you.. I guess I got it. I was wondering if there was anyway to do it with in-built functions..
