### ISSUE TITLE
NeDB become slow with a big database

### ISSUE THREAD

**Issue by solisoft** [louischatriot/nedb#424] opened 2016-05-26 08:57 UTC
I'm trying to insert a 150Mb of data from a file (1 500 000 lines to import)
But it's really slow to load ...

There is any limitations ?

**Comment by louischatriot** [comment] 2016-05-27 10:20
Not really except RAM limitations but 150 MB of data must take quite some time to load since the entire file needs to be loaded in emory. If you tell me what are the metrics (time it takes and so on) we can tell you if that's normal, which I suspect it is.

Closing this meanwhile.

**Closed by louischatriot** 2016-05-27 10:20 UTC

**Comment by solisoft** [comment] 2016-05-27 14:06
The take about 30s to load data... then any read in the DB is quite slow (maybe missing indexes, though)

**Comment by louischatriot** [comment] 2016-05-27 14:18
that's very slow indeed, and probably has to do with your hardware. Maybe your antivirus software is the cause, otherwise it's impossible for me to help you since I don't have your machine ...

**Comment by solisoft** [comment] 2016-05-27 14:20
My hardware : Mac Book Pro 8Go i7 with SSD
Also, no antivirus... and the app is an electron one... not sure it's because of my hardware ...

**Comment by Anenth** [comment] 2019-12-12 12:27
The same issue, it too slow, it takes 2mins to load

**Comment by Sandhya1007** [comment] 2022-01-25 07:40
Same is with my application. The application is built in electron with react js integration and I am using nedb to store data but it's taking more than 5 minutes to load.
